name: Ostorlab Security Scanner
description: Scan mobile apps for outdated dependencies, hardcoded secrets, privacy leakages, and insecure code (Signup at ostorlab.co).
inputs:
  scan_profile:
    description: Specifies your scan profile ( free "fast_scan" for community scans and "full_scan" for full analysis)
    required: true
    default: fast_scan
  asset_type:
    description: Type of asset to scan. (['android-apk', 'android-aab', 'ios-ipa'])
    required: true
  target:
    description: Path to file .apk|.ios file.
    required: true
  scan_title:
    description: Title for your scan.
    required: false
  ostorlab_api_key:
    description: Api key from ostorlab.
    required: true
  break_on_risk_rating:
    description: Wait for the scan results and force the action to fail if the scan risk rating is equal or higher this value. (['HIGH', 'MEDIUM', 'LOW','POTENTIALLY])
    required: false
  max_wait_minutes:
    description: Specifies the maximum number of minutes to wait for scan results.
    required: false
outputs:
  scan_id:
    description: id of the created scan.
  status:
    description: status of scan.
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "shield"
  color: "blue"
